"""Schemas for everything under data/ (lightweight rule 2).

Numbers live in data files so they can change without a code release, which also means
nothing checks them unless something here does. Each file shape has a Pydantic model; the
tests validate every data file against its model, fail on any file no model covers, and
check that the JSON Schemas in data/schema/ are the ones these models export - so a third
party correcting a bandwidth can validate their edit without reading this code.

Nothing here runs when rightsize is imported or used: load_yaml stays a plain read, and
validation is a test and CI concern.

    python -c "from rightsize.data_models import validate_all; print(validate_all())"
"""

from __future__ import annotations

import datetime as _dt
import fnmatch
import re
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, ValidationError, field_validator, model_validator

Vendor = Literal["nvidia", "amd", "intel", "apple", "qualcomm", "cpu", "other"]


class _Strict(BaseModel):
    # a misspelt key is a silent no-op in YAML; refuse it instead
    model_config = ConfigDict(extra="forbid")


class Source(_Strict):
    """Where a number came from. Required on every record (lightweight rule 2)."""

    source_url: str
    fetched_at: str
    hand: bool = False
    note: str | None = None

    @field_validator("source_url")
    @classmethod
    def _https(cls, v: str) -> str:
        if not v.startswith("https://"):
            raise ValueError("source_url must be an https:// link someone can open")
        return v

    @field_validator("fetched_at")
    @classmethod
    def _iso_date(cls, v: str) -> str:
        _dt.date.fromisoformat(str(v))
        return str(v)


# ---------------------------------------------------------------- quants


class GgufBpwFile(_Strict):
    """data/quants/gguf_bpw.yaml: real bits per weight, scales and mins included."""

    provenance: Source
    tensor_types: dict[str, float]
    file_types_provenance: Source
    file_types: dict[str, float]

    @field_validator("tensor_types", "file_types")
    @classmethod
    def _plausible_bpw(cls, v: dict[str, float]) -> dict[str, float]:
        bad = {k: x for k, x in v.items() if not 1.0 <= x <= 32.0}
        if bad:
            raise ValueError(f"bits per weight outside 1-32: {bad}")
        return v


class GgmlTensorType(_Strict):
    id: int = Field(ge=0)
    name: str
    block_size: int = Field(gt=0, description="weights per block")
    type_size: int = Field(gt=0, description="bytes per block, scales included")


class GgufFileType(_Strict):
    id: int = Field(ge=0)
    name: str


class GgmlTypesFile(_Strict):
    """data/quants/ggml_types.yaml: the numbers a GGUF header uses for tensor and file types,
    generated by scripts/ingest_ggml_types.py."""

    provenance: Source
    llama_cpp: str
    tensor_types: list[GgmlTensorType] = Field(min_length=1)
    file_types: list[GgufFileType] = Field(min_length=1)

    @model_validator(mode="after")
    def _unique(self) -> GgmlTypesFile:
        for label, rows in (("tensor", self.tensor_types), ("file", self.file_types)):
            for attr in ("id", "name"):
                values = [getattr(r, attr) for r in rows]
                dupes = sorted({str(x) for x in values if values.count(x) > 1})
                if dupes:
                    raise ValueError(f"{label} type {attr} used twice: {dupes}")
        return self


# ---------------------------------------------------------------- hardware


class PresetRecord(_Strict):
    name: str
    vendor: Vendor
    memory_gib: float = Field(gt=0, description="as the vendor states it: a 16GB card is 16")
    bandwidth_gbps: float | None = Field(default=None, gt=0)
    compute_arch: str | None = None
    compute_capability: float | None = None
    backends: list[str] = Field(default_factory=list)
    usable_fraction: float = Field(default=1.0, gt=0, le=1)
    unified_memory: bool = False
    os: str | None = None
    system_ram_gib: float | None = Field(default=None, gt=0)
    provenance: Source


class PresetsFile(_Strict):
    """data/hardware/presets.yaml: complete, curated setups."""

    presets: list[PresetRecord]

    @field_validator("presets")
    @classmethod
    def _unique(cls, v: list[PresetRecord]) -> list[PresetRecord]:
        names = [p.name for p in v]
        if len(names) != len(set(names)):
            raise ValueError("duplicate preset names")
        return v


class CatalogRecord(_Strict):
    sku: list[str] = Field(min_length=3, max_length=3)
    kind: Literal["gpu", "cpu", "apple"]
    vendor: Vendor
    name: str
    memory_gib: list[float] | None = None
    tflops: float | None = None
    compute_capability: float | None = None
    gfx_version: str | None = None
    msrp_usd: float | None = None
    power_w: float | None = None
    release_year: int | None = None
    provenance: Source


class GpuCatalogFile(_Strict):
    """data/hardware/gpus.yaml, generated by scripts/ingest_hf_hardware.py."""

    devices: list[CatalogRecord]


class BandwidthRecord(_Strict):
    name: str
    vendor: Vendor | None = None
    match: str | None = None
    aliases: list[str] = Field(default_factory=list)
    memory_type: str | None = None
    bus_width_bits: float | None = Field(default=None, gt=0)
    memory_speed_gbps: float | None = Field(default=None, gt=0)
    bandwidth_gbps: float | None = Field(default=None, gt=0)
    stated_gbps: float | None = None
    stated: bool = False
    source_disagrees: bool = False
    note: str | None = None
    provenance: Source

    @model_validator(mode="after")
    def _derivable(self) -> BandwidthRecord:
        # a record is only useful if a bandwidth comes out of it one way or the other
        if self.bandwidth_gbps is None and not (self.bus_width_bits and self.memory_speed_gbps):
            raise ValueError("needs bandwidth_gbps, or bus_width_bits and memory_speed_gbps")
        return self


class BandwidthFile(_Strict):
    """data/hardware/bandwidth.yaml (hand-checked) and bandwidth_wikipedia.yaml (ingested)."""

    formula_id: str
    sources: dict[str, str] | None = None
    devices: list[BandwidthRecord]


# ---------------------------------------------------------------- quality


class _KldBand(_Strict):
    pass_below: float = Field(gt=0)
    warn_below: float = Field(gt=0)


class _AgreementBand(_Strict):
    pass_above: float = Field(gt=0, le=1)
    warn_above: float = Field(gt=0, le=1)


class GateThresholdsFile(_Strict):
    """data/quality/gate_thresholds.yaml: the quantization quality gate (F8)."""

    provenance: Source
    kld: _KldBand
    top1_agreement: _AgreementBand

    @model_validator(mode="after")
    def _ordered(self) -> GateThresholdsFile:
        if not self.kld.pass_below < self.kld.warn_below:
            raise ValueError("kld: pass_below must be below warn_below")
        if not self.top1_agreement.pass_above > self.top1_agreement.warn_above:
            raise ValueError("top1_agreement: pass_above must be above warn_above")
        return self


class _TypeMeasures(_Strict):
    bpw: float | None = Field(default=None, ge=1, le=32)
    ppl_delta: float | None = None
    ppl_reference: str | None = None
    requires_imatrix: bool | None = None


class GgufTypesFile(_Strict):
    """data/quality/gguf_types.yaml, generated from llama.cpp's own measurements."""

    llama_cpp: str
    sources: dict[str, Source]
    file_types: dict[str, _TypeMeasures]


class _FloorRow(_Strict):
    params_b: float = Field(gt=0)
    qlora_gb: float = Field(gt=0)
    lora_gb: float = Field(gt=0)


class FinetuneFloorsFile(_Strict):
    """data/finetune/unsloth_vram.yaml: published minimum VRAM for LoRA and QLoRA."""

    provenance: Source
    rows: list[_FloorRow]

    @field_validator("rows")
    @classmethod
    def _monotonic(cls, v: list[_FloorRow]) -> list[_FloorRow]:
        # interpolation between rows assumes memory never falls as models grow
        ordered = sorted(v, key=lambda r: r.params_b)
        for a, b in zip(ordered, ordered[1:], strict=False):
            if b.qlora_gb < a.qlora_gb or b.lora_gb < a.lora_gb:
                raise ValueError(f"memory falls between {a.params_b}B and {b.params_b}B")
        return v


# ---------------------------------------------------------------- rules


class _RuleTest(_Strict):
    fires: dict[str, Any]
    silent: dict[str, Any]


class RuleRecord(_Strict):
    id: str = Field(pattern=r"^[a-z0-9_]+$")
    applies_to: dict[str, Any] = Field(default_factory=dict)
    condition: str | None = None
    effect: Literal["block", "penalize", "require", "note"]
    penalty: float | None = Field(default=None, gt=0, lt=1)
    requires: str | None = None
    message: str
    source_url: str
    test: _RuleTest

    @field_validator("source_url")
    @classmethod
    def _https(cls, v: str) -> str:
        if not v.startswith("https://"):
            raise ValueError("source_url must be an https:// link someone can open")
        return v

    @field_validator("condition")
    @classmethod
    def _parses(cls, v: str | None) -> str | None:
        if v is not None:
            from rightsize.rules.expr import Condition

            Condition(v)  # raises ExprError, a ValueError, on anything not allowed
        return v

    @model_validator(mode="after")
    def _effect_fields(self) -> RuleRecord:
        if (self.effect == "penalize") != (self.penalty is not None):
            raise ValueError("penalty goes with effect: penalize, and only with it")
        if (self.effect == "require") != (self.requires is not None):
            raise ValueError("requires goes with effect: require, and only with it")
        return self


class RulesFile(_Strict):
    """data/rules/*.yaml: gates, penalties and requirements, each with a source and tests."""

    rules: list[RuleRecord] = Field(min_length=1)


# ---------------------------------------------------------------- models


class _CandidateFacts(_Strict):
    params_total: int = Field(gt=0)
    params_active: int | None = None
    num_layers: int = Field(gt=0)
    num_kv_heads: int = Field(gt=0)
    head_dim: int = Field(gt=0)
    context_max: int | None = None
    dtype: str | None = None
    extra: dict[str, Any] = Field(default_factory=dict)


class Candidate(_Strict):
    repo: str
    facts_from: str
    publisher: str
    tasks: list[Literal["chat", "coding"]] = Field(min_length=1)
    created_at: str
    downloads_30d: int = Field(ge=0)
    gated: bool | str = False
    license: str | None = None
    facts: _CandidateFacts


FamilyName = Literal["diffusion", "audio", "vision", "embedding"]


class CuratedModel(_Strict):
    repo: str
    family: FamilyName
    tasks: list[str] = Field(min_length=1)
    publisher: str
    params_total: int = Field(gt=0)
    library: str | None = None
    license: str | list[str] | None = None
    gated: bool | str = False
    created_at: str
    downloads_30d: int = Field(ge=0)


class FamiliesFile(_Strict):
    """data/models/families.yaml, generated by scripts/ingest_families.py."""

    provenance: Source
    tasks: dict[FamilyName, list[str]]
    models: list[CuratedModel] = Field(min_length=1)

    @model_validator(mode="after")
    def _tasks_known(self) -> FamiliesFile:
        for m in self.models:
            unknown = set(m.tasks) - set(self.tasks[m.family])
            if unknown:
                raise ValueError(f"{m.repo}: tasks not listed for {m.family}: {sorted(unknown)}")
        return self


class VariantFormat(_Strict):
    id: str
    label: str
    tags: list[str] = Field(default_factory=list, description="Hub tags, any case")
    libraries: list[str] = Field(default_factory=list, description="Hub library_name values")
    name_patterns: list[str] = Field(default_factory=list, description="regexes on the repo name")
    quant_patterns: list[str] = Field(
        default_factory=list, description="regexes whose first group is the quantization"
    )
    runtimes: list[str] = Field(default_factory=list)
    source: Source

    @field_validator("name_patterns", "quant_patterns")
    @classmethod
    def _compiles(cls, v: list[str]) -> list[str]:
        for pattern in v:
            re.compile(pattern)
        return v


class QuantPublisher(_Strict):
    name: str
    formats: list[str]
    note: str
    source: Source


class VariantsFile(_Strict):
    """data/models/variants.yaml: how quantized copies of a model are published on the Hub."""

    provenance: Source
    strip_patterns: list[str] = Field(min_length=1)
    formats: list[VariantFormat] = Field(min_length=1)
    publishers: list[QuantPublisher] = Field(default_factory=list)

    @model_validator(mode="after")
    def _consistent(self) -> VariantsFile:
        for pattern in self.strip_patterns:
            re.compile(pattern)
        ids = [f.id for f in self.formats]
        dupes = sorted({i for i in ids if ids.count(i) > 1})
        if dupes:
            raise ValueError(f"format id used twice: {dupes}")
        unknown = sorted({f for p in self.publishers for f in p.formats} - set(ids))
        if unknown:
            raise ValueError(f"publishers name formats the table does not have: {unknown}")
        return self


class CandidatesFile(_Strict):
    """data/models/candidates.yaml, generated by scripts/ingest_candidates.py."""

    provenance: Source
    superseded: list[str] = Field(default_factory=list)
    models: list[Candidate] = Field(min_length=1)


# ---------------------------------------------------------------- runtimes


class _Sliding(_Strict):
    pattern: int = Field(ge=1)
    window_key: str | None = None
    window_default: int | None = Field(default=None, gt=0)


class _Hybrid(_Strict):
    rule: Literal[
        "full_attention_interval", "attn_layer_period", "hybrid_override_pattern",
        "layer_types", "parallel",
    ]
    interval_default: int | None = None


class KvRule(_Strict):
    model_types: list[str] = Field(min_length=1)
    sliding: _Sliding | None = None
    mla: bool = False
    hybrid: _Hybrid | None = None
    note: str | None = None
    source_url: str

    @model_validator(mode="after")
    def _one_layout(self) -> KvRule:
        if sum([self.sliding is not None, self.mla, self.hybrid is not None]) != 1:
            raise ValueError("a rule sets exactly one of sliding, mla or hybrid")
        return self


class _KvDefaults(_Strict):
    n_ubatch: int = Field(gt=0)
    swa_pad: int = Field(gt=0)
    recurrent_state_bytes: int = Field(gt=0)
    swa_source_url: str


class KvCacheFile(_Strict):
    """data/runtimes/<runtime>/kv_cache.yaml: how a runtime lays out the KV cache (F3)."""

    runtime: str
    version: str
    source_url: str
    fetched_at: str
    defaults: _KvDefaults
    architectures: list[KvRule]

    @field_validator("architectures")
    @classmethod
    def _no_overlap(cls, v: list[KvRule]) -> list[KvRule]:
        seen: set[str] = set()
        for rule in v:
            clash = seen.intersection(rule.model_types)
            if clash:
                raise ValueError(f"model types claimed by two rules: {sorted(clash)}")
            seen.update(rule.model_types)
        return v


# ---------------------------------------------------------------- other families (F3)


class FormatRecord(_Strict):
    id: str
    bpw: float = Field(ge=1.0, le=32.0)
    aliases: list[str] = Field(default_factory=list)
    layout: str = Field(description="how the bits add up, so the figure can be checked")
    source: Source


class FormatsFile(_Strict):
    """data/quants/formats.yaml: bits per weight for weight formats other than GGUF."""

    formats: list[FormatRecord]

    @field_validator("formats")
    @classmethod
    def _unique_names(cls, v: list[FormatRecord]) -> list[FormatRecord]:
        seen: set[str] = set()
        for f in v:
            for name in (f.id, *f.aliases):
                key = name.lower()
                if key in seen:
                    raise ValueError(f"format name used twice: {name}")
                seen.add(key)
        return v


class _DiffusersConstants(_Strict):
    vae_decode_bytes_per_pixel: float = Field(gt=0)
    unet_bytes_per_latent_pixel: float = Field(gt=0)
    dit_activation_factor: float = Field(gt=0)
    text_encode_gb: float = Field(ge=0)
    default_text_tokens: int = Field(gt=0)
    sequential_resident_gb: float = Field(gt=0)
    cuda_context_gb: float = Field(ge=0)
    allocator_slack: float = Field(ge=0, lt=1)


class DiffusionMeasurement(_Strict):
    """One published peak-memory figure for a pipeline, replayed by the tests."""

    id: str
    source_url: str
    model: str
    hardware: str
    metric: Literal["max_memory_reserved", "max_memory_allocated", "unspecified"]
    resolution: tuple[int, int]
    batch: int = Field(ge=1)
    offload: Literal["none", "model", "sequential"]
    vae_slicing: bool = False
    quant: dict[str, str] = Field(description="component -> format; others stay 16-bit")
    after_loading_gib: float | None = Field(default=None, gt=0)
    peak_gib: float = Field(gt=0)
    tolerance: float = Field(gt=0, le=0.5, description="relative error the estimate may have")
    note: str | None = None

    @field_validator("source_url")
    @classmethod
    def _https(cls, v: str) -> str:
        if not v.startswith("https://"):
            raise ValueError("source_url must be an https:// link someone can open")
        return v


class DiffusersMemoryFile(_Strict):
    """data/runtimes/diffusers/memory.yaml: the diffusion memory model and its evidence."""

    constants: _DiffusersConstants
    constants_source: Source
    measurements: list[DiffusionMeasurement]


class _WhisperCurveRow(_Strict):
    model: str
    disk_mib: float = Field(gt=0)
    memory_mb: float = Field(gt=0)


class _WhisperCurve(_Strict):
    source: Source
    rows: list[_WhisperCurveRow]


class WhisperRow(_Strict):
    runtime: Literal["whisper.cpp", "faster-whisper", "transformers", "openai-whisper"]
    model: str
    params: int = Field(gt=0)
    device: Literal["gpu", "cpu"]
    precision: str
    batch: int = Field(ge=1)
    memory_mb: float = Field(gt=0)


class _WhisperMeasurements(_Strict):
    source: Source
    rows: list[WhisperRow]


class WhisperMemoryFile(_Strict):
    """data/runtimes/whisper/memory.yaml: Whisper memory per runtime, and its evidence."""

    size_exponent: float = Field(gt=0, lt=1)
    size_curve: _WhisperCurve
    measurements: _WhisperMeasurements


# ---------------------------------------------------------------- runtime overheads (F3, F9)


class RuntimeOverhead(_Strict):
    name: str
    fixed_gb: float = Field(ge=0, le=10)
    fraction: float = Field(ge=0, lt=1)
    source: Source


class OverheadsFile(_Strict):
    """data/runtimes/overheads.yaml: memory a runtime adds beyond weights and KV cache."""

    runtimes: list[RuntimeOverhead]


# ---------------------------------------------------------------- cloud (F7)


class GpuTflopsRecord(_Strict):
    names: list[str] = Field(min_length=1, description="SkyPilot catalog accelerator names")
    tflops: float = Field(gt=0, description="dense 16-bit tensor TFLOPS")
    source_url: str
    note: str

    @field_validator("source_url")
    @classmethod
    def _https(cls, v: str) -> str:
        if not v.startswith("https://"):
            raise ValueError("source_url must be an https:// link someone can open")
        return v


class GpuTflopsFile(_Strict):
    """data/cloud/gpu_tflops.yaml: datasheet tensor throughput for the job-time estimate."""

    gpus: list[GpuTflopsRecord]

    @field_validator("gpus")
    @classmethod
    def _one_row_per_name(cls, v: list[GpuTflopsRecord]) -> list[GpuTflopsRecord]:
        seen: set[str] = set()
        for rec in v:
            clash = seen.intersection(rec.names)
            if clash:
                raise ValueError(f"names in two rows: {sorted(clash)}")
            seen.update(rec.names)
        return v


# ---------------------------------------------------------------- registry


def _recipe_model() -> type[BaseModel]:
    from rightsize.registry.schema import Recipe

    return Recipe


def _framework_model() -> type[BaseModel]:
    from rightsize.registry.schema import FrameworkInfo

    return FrameworkInfo


#: Models that live in rightsize.registry, resolved on first use.
_LAZY = (_recipe_model, _framework_model)


#: data/ path pattern -> (schema file name, model). Every YAML file under data/ must match
#: one of these; tests fail on a file nothing covers.
DATA_FILES: dict[str, tuple[str, Any]] = {
    "quants/gguf_bpw.yaml": ("gguf_bpw", GgufBpwFile),
    "quants/ggml_types.yaml": ("ggml_types", GgmlTypesFile),
    "quants/formats.yaml": ("formats", FormatsFile),
    "runtimes/diffusers/memory.yaml": ("diffusers_memory", DiffusersMemoryFile),
    "runtimes/whisper/memory.yaml": ("whisper_memory", WhisperMemoryFile),
    "cloud/gpu_tflops.yaml": ("gpu_tflops", GpuTflopsFile),
    "runtimes/overheads.yaml": ("overheads", OverheadsFile),
    "hardware/presets.yaml": ("presets", PresetsFile),
    "hardware/gpus.yaml": ("gpu_catalog", GpuCatalogFile),
    "hardware/bandwidth*.yaml": ("bandwidth", BandwidthFile),
    "quality/gate_thresholds.yaml": ("gate_thresholds", GateThresholdsFile),
    "quality/gguf_types.yaml": ("gguf_types", GgufTypesFile),
    "finetune/unsloth_vram.yaml": ("finetune_floors", FinetuneFloorsFile),
    "models/candidates.yaml": ("candidates", CandidatesFile),
    "models/variants.yaml": ("variants", VariantsFile),
    "models/families.yaml": ("families", FamiliesFile),
    "rules/*.yaml": ("rules", RulesFile),
    "runtimes/*/kv_cache.yaml": ("kv_cache", KvCacheFile),
    # first match wins: a framework's descriptor sits beside its recipes
    "recipes/*/framework.yaml": ("framework", _framework_model),
    "recipes/*/*.yaml": ("recipe", _recipe_model),
}


def model_for(relative: str) -> tuple[str, type[BaseModel]] | None:
    for pattern, (name, model) in DATA_FILES.items():
        if fnmatch.fnmatch(relative, pattern):
            return name, (model() if model in _LAZY else model)
    return None


def validate_all(root: str | Path | None = None) -> list[str]:
    """Every problem across data/, as readable lines. Empty means clean."""
    import yaml

    from rightsize._data import data_dir

    base = Path(root) if root else data_dir()
    problems: list[str] = []
    for path in sorted(base.rglob("*.yaml")):
        rel = path.relative_to(base).as_posix()
        found = model_for(rel)
        if found is None:
            problems.append(f"{rel}: no schema covers this file (add it to DATA_FILES)")
            continue
        _, model = found
        try:
            model.model_validate(yaml.safe_load(path.read_text(encoding="utf-8")))
        except ValidationError as exc:
            for err in exc.errors()[:5]:
                where = ".".join(str(p) for p in err["loc"])
                problems.append(f"{rel}: {where}: {err['msg']}")
    return problems


def json_schemas() -> dict[str, dict[str, Any]]:
    """Schema name -> JSON Schema, as written to data/schema/ by scripts/export_schemas.py."""
    out: dict[str, dict[str, Any]] = {}
    for name, model in DATA_FILES.values():
        m = model() if model in _LAZY else model
        out[name] = m.model_json_schema()
    return out
