"""Record how GGUF files number their tensor types and file types (F1).

    uv run python scripts/ingest_ggml_types.py

A GGUF header names each tensor's type by number (12 is Q4_K) and the whole file's mix by
another number (``general.file_type``, 15 is Q4_K_M). Reading a header needs both tables,
and llama.cpp adds types as it goes: NVFP4, Q1_0 and Q2_0 are newer than most readers. The
tables come from ``gguf-py/gguf/constants.py`` at the llama.cpp tag we pin, which the
llama.cpp project keeps equal to ggml.h and llama.h ("ALL VALUES SHOULD BE THE SAME HERE AS
THEY ARE OVER THERE"). ``rightsize data update`` can then teach an installed release a new
type without a new release of the code.
"""

from __future__ import annotations

import ast
import datetime as dt
import re
import sys
from pathlib import Path

import httpx
import yaml

from rightsize.data_models import GgmlTypesFile
from rightsize.execution.install import LLAMA_CPP_VERSION

OUT = Path(__file__).resolve().parents[1] / "data" / "quants" / "ggml_types.yaml"
RAW = "https://raw.githubusercontent.com/ggml-org/llama.cpp/{tag}/gguf-py/gguf/constants.py"
PAGE = "https://github.com/ggml-org/llama.cpp/blob/{tag}/gguf-py/gguf/constants.py"

_MEMBER = re.compile(r"^\s{4}([A-Z][A-Z0-9_]*)\s*=\s*(\d+)\b", re.M)
_SIZE = re.compile(r"GGMLQuantizationType\.([A-Z0-9_]+):\s*\((.+)\),\s*$", re.M)


def _block(text: str, header: str) -> str:
    """The body of one class or dict, up to the first line that is not indented."""
    start = text.index(header)
    lines = text[start:].splitlines()[1:]
    body = []
    for line in lines:
        if line and not line.startswith((" ", "\t")):
            break
        body.append(line)
    return "\n".join(body)


def _arith(node: ast.AST, names: dict[str, int]) -> int:
    """Integer arithmetic over literals and known names: the size expressions
    (``2 + QK_K // 4``) and nothing else."""
    if isinstance(node, ast.Constant) and isinstance(node.value, int):
        return node.value
    if isinstance(node, ast.Name) and node.id in names:
        return names[node.id]
    if isinstance(node, ast.BinOp):
        a, b = _arith(node.left, names), _arith(node.right, names)
        ops = {ast.Add: a + b, ast.Sub: a - b, ast.Mult: a * b}
        if isinstance(node.op, ast.FloorDiv):
            return a // b
        if type(node.op) in ops:
            return ops[type(node.op)]
    raise ValueError(f"unexpected expression: {ast.dump(node)}")


def parse(text: str) -> dict:
    qk_k = int(re.search(r"^QK_K\s*=\s*(\d+)", text, re.M).group(1))
    ids = {name: int(n) for name, n in _MEMBER.findall(
        _block(text, "class GGMLQuantizationType(IntEnum):"))}
    sizes = {}
    for name, pair in _SIZE.findall(_block(text, "GGML_QUANT_SIZES:")):
        tup = ast.parse(f"({pair})", mode="eval").body
        block, size = (_arith(e, {"QK_K": qk_k}) for e in tup.elts)
        sizes[name] = (block, size)
    missing = sorted(set(ids) - set(sizes))
    if missing:
        raise SystemExit(f"types without a size in GGML_QUANT_SIZES: {missing}")
    tensor_types = [
        {"id": i, "name": name, "block_size": sizes[name][0], "type_size": sizes[name][1]}
        for name, i in sorted(ids.items(), key=lambda kv: kv[1])
    ]
    file_types = []
    for name, i in _MEMBER.findall(_block(text, "class LlamaFileType(IntEnum):")):
        if name == "GUESSED":
            continue
        short = name.removeprefix("MOSTLY_").removeprefix("ALL_")
        file_types.append({"id": int(i), "name": short})
    return {"tensor_types": tensor_types, "file_types": file_types}


def main() -> int:
    tag = LLAMA_CPP_VERSION
    text = httpx.get(RAW.format(tag=tag), timeout=60, follow_redirects=True).text
    doc = {
        "provenance": {
            "source_url": PAGE.format(tag=tag),
            "fetched_at": dt.date.today().isoformat(),
            "note": "GGMLQuantizationType, GGML_QUANT_SIZES and LlamaFileType; "
                    "generated by scripts/ingest_ggml_types.py",
        },
        "llama_cpp": tag,
        **parse(text),
    }
    GgmlTypesFile.model_validate(doc)
    header = (
        "# GGUF tensor types and file types by number, from llama.cpp's gguf-py at the pinned\n"
        "# tag. bits per weight = type_size * 8 / block_size. Generated by\n"
        "# scripts/ingest_ggml_types.py - do not hand edit.\n"
    )
    # provenance as a block, one type per line
    text = yaml.safe_dump({k: doc[k] for k in ("provenance", "llama_cpp")}, sort_keys=False)
    for key in ("tensor_types", "file_types"):
        text += yaml.safe_dump({key: doc[key]}, sort_keys=False, default_flow_style=None)
    OUT.write_text(header + text, encoding="utf-8")
    print(f"{len(doc['tensor_types'])} tensor types, {len(doc['file_types'])} file types ({tag})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
